/* ============================================================
   Elenco Europeo dei Rifiuti (EER, ex CER) — dataset per la ricerca
   c = codice, d = descrizione, p = pericoloso (true/false)
   ch = true → capitolo (intestazione a due cifre)
   Copertura: tutti i 20 capitoli + i codici di uso più frequente
   nella gestione dei rifiuti speciali. Elenco a scopo informativo:
   non sostituisce la classificazione ufficiale del rifiuto.
   ============================================================ */
window.CER_DATA = [
  /* ---------- 01 ---------- */
  { c: "01", d: "Rifiuti derivanti da prospezione, estrazione da miniera o cava, trattamento fisico o chimico di minerali", ch: true },
  { c: "01 01 01", d: "Rifiuti da estrazione di minerali metalliferi", p: false },
  { c: "01 01 02", d: "Rifiuti da estrazione di minerali non metalliferi", p: false },
  { c: "01 04 08", d: "Scarti di ghiaia e pietrisco, diversi da quelli di cui alla voce 01 04 07", p: false },
  { c: "01 04 09", d: "Scarti di sabbia e argilla", p: false },
  { c: "01 04 13", d: "Rifiuti prodotti dalla lavorazione della pietra, diversi da quelli di cui alla voce 01 04 07", p: false },
  { c: "01 05 04", d: "Fanghi e rifiuti di perforazione di pozzi per acque dolci", p: false },

  /* ---------- 02 ---------- */
  { c: "02", d: "Rifiuti prodotti da agricoltura, orticoltura, acquacoltura, selvicoltura, caccia e pesca, trattamento e preparazione di alimenti", ch: true },
  { c: "02 01 01", d: "Fanghi da operazioni di lavaggio e pulizia", p: false },
  { c: "02 01 03", d: "Scarti di tessuti vegetali", p: false },
  { c: "02 01 04", d: "Rifiuti plastici (ad esclusione degli imballaggi)", p: false },
  { c: "02 01 06", d: "Feci animali, urine e letame, effluenti raccolti separatamente e trattati fuori sito", p: false },
  { c: "02 01 08", d: "Rifiuti agrochimici contenenti sostanze pericolose", p: true },
  { c: "02 01 09", d: "Rifiuti agrochimici diversi da quelli di cui alla voce 02 01 08", p: false },
  { c: "02 01 10", d: "Rifiuti metallici", p: false },
  { c: "02 02 03", d: "Scarti inutilizzabili per il consumo o la trasformazione", p: false },
  { c: "02 02 04", d: "Fanghi prodotti dal trattamento in loco degli effluenti", p: false },
  { c: "02 03 04", d: "Scarti inutilizzabili per il consumo o la trasformazione", p: false },
  { c: "02 05 01", d: "Scarti inutilizzabili per il consumo o la trasformazione (industria lattiero-casearia)", p: false },
  { c: "02 06 01", d: "Scarti inutilizzabili per il consumo o la trasformazione (prodotti da forno e dolciari)", p: false },
  { c: "02 07 04", d: "Scarti inutilizzabili per il consumo o la trasformazione (bevande)", p: false },

  /* ---------- 03 ---------- */
  { c: "03", d: "Rifiuti della lavorazione del legno e della produzione di pannelli, mobili, polpa, carta e cartone", ch: true },
  { c: "03 01 01", d: "Scarti di corteccia e sughero", p: false },
  { c: "03 01 04", d: "Segatura, trucioli, residui di taglio, legno, pannelli e piallacci contenenti sostanze pericolose", p: true },
  { c: "03 01 05", d: "Segatura, trucioli, residui di taglio, legno, pannelli di truciolare e piallacci diversi da quelli di cui alla voce 03 01 04", p: false },
  { c: "03 03 01", d: "Scarti di corteccia e legno", p: false },
  { c: "03 03 07", d: "Scarti della separazione meccanica nella produzione di polpa da rifiuti di carta e cartone", p: false },
  { c: "03 03 08", d: "Scarti della selezione di carta e cartone destinati ad essere riciclati", p: false },

  /* ---------- 04 ---------- */
  { c: "04", d: "Rifiuti della lavorazione di pelli e pellicce e dell'industria tessile", ch: true },
  { c: "04 01 08", d: "Cuoio conciato (scarti, cascami, ritagli, polveri di lucidatura) contenente cromo", p: false },
  { c: "04 02 09", d: "Rifiuti da materiali compositi (fibre impregnate, elastomeri, plastomeri)", p: false },
  { c: "04 02 21", d: "Rifiuti da fibre tessili grezze", p: false },
  { c: "04 02 22", d: "Rifiuti da fibre tessili lavorate", p: false },

  /* ---------- 05 ---------- */
  { c: "05", d: "Rifiuti della raffinazione del petrolio, purificazione del gas naturale e trattamento pirolitico del carbone", ch: true },
  { c: "05 01 03", d: "Morchie da fondi di serbatoi", p: true },
  { c: "05 01 05", d: "Perdite di olio", p: true },
  { c: "05 01 06", d: "Fanghi oleosi prodotti dalla manutenzione di impianti e apparecchiature", p: true },
  { c: "05 01 09", d: "Fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose", p: true },
  { c: "05 01 10", d: "Fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 05 01 09", p: false },

  /* ---------- 06 ---------- */
  { c: "06", d: "Rifiuti dei processi chimici inorganici", ch: true },
  { c: "06 01 01", d: "Acido solforico e acido solforoso", p: true },
  { c: "06 01 02", d: "Acido cloridrico", p: true },
  { c: "06 01 04", d: "Acido fosforico e fosforoso", p: true },
  { c: "06 01 05", d: "Acido nitrico e acido nitroso", p: true },
  { c: "06 01 06", d: "Altri acidi", p: true },
  { c: "06 02 01", d: "Idrossido di calcio", p: true },
  { c: "06 02 04", d: "Idrossido di sodio e di potassio", p: true },
  { c: "06 02 05", d: "Altre basi", p: true },
  { c: "06 03 13", d: "Sali e loro soluzioni, contenenti metalli pesanti", p: true },
  { c: "06 03 14", d: "Sali e loro soluzioni, diversi da quelli di cui alle voci 06 03 11 e 06 03 13", p: false },
  { c: "06 04 04", d: "Rifiuti contenenti mercurio", p: true },
  { c: "06 04 05", d: "Rifiuti contenenti altri metalli pesanti", p: true },
  { c: "06 13 02", d: "Carbone attivato esaurito (tranne 06 07 02)", p: true },

  /* ---------- 07 ---------- */
  { c: "07", d: "Rifiuti dei processi chimici organici", ch: true },
  { c: "07 01 01", d: "Soluzioni acquose di lavaggio e acque madri", p: true },
  { c: "07 01 03", d: "Solventi organici alogenati, soluzioni di lavaggio e acque madri", p: true },
  { c: "07 01 04", d: "Altri solventi organici, soluzioni di lavaggio e acque madri", p: true },
  { c: "07 01 11", d: "Fanghi prodotti dal trattamento in loco degli effluenti, contenenti sostanze pericolose", p: true },
  { c: "07 01 12", d: "Fanghi prodotti dal trattamento in loco degli effluenti, diversi da quelli di cui alla voce 07 01 11", p: false },
  { c: "07 02 13", d: "Rifiuti plastici", p: false },
  { c: "07 02 17", d: "Rifiuti contenenti silicone diversi da quelli di cui alla voce 07 02 16", p: false },
  { c: "07 03 04", d: "Altri solventi organici, soluzioni di lavaggio e acque madri (coloranti e pigmenti)", p: true },
  { c: "07 05 13", d: "Rifiuti solidi contenenti sostanze pericolose (farmaceutici)", p: true },
  { c: "07 05 14", d: "Rifiuti solidi diversi da quelli di cui alla voce 07 05 13", p: false },
  { c: "07 06 04", d: "Altri solventi organici, soluzioni di lavaggio e acque madri (saponi, detergenti, cosmetici)", p: true },

  /* ---------- 08 ---------- */
  { c: "08", d: "Rifiuti della produzione, formulazione, fornitura e uso di rivestimenti (pitture, vernici e smalti vetrati), adesivi, sigillanti e inchiostri per stampa", ch: true },
  { c: "08 01 11", d: "Pitture e vernici di scarto contenenti solventi organici o altre sostanze pericolose", p: true },
  { c: "08 01 12", d: "Pitture e vernici di scarto diverse da quelle di cui alla voce 08 01 11", p: false },
  { c: "08 01 13", d: "Fanghi prodotti da pitture e vernici contenenti solventi organici o altre sostanze pericolose", p: true },
  { c: "08 01 15", d: "Fanghi acquosi contenenti pitture e vernici con solventi organici o altre sostanze pericolose", p: true },
  { c: "08 01 17", d: "Fanghi prodotti dalla rimozione di pitture e vernici contenenti solventi organici o altre sostanze pericolose", p: true },
  { c: "08 01 18", d: "Fanghi prodotti dalla rimozione di pitture e vernici, diversi da quelli di cui alla voce 08 01 17", p: false },
  { c: "08 01 21", d: "Residui di vernici o di sverniciatori", p: true },
  { c: "08 03 12", d: "Scarti di inchiostro contenenti sostanze pericolose", p: true },
  { c: "08 03 13", d: "Scarti di inchiostro diversi da quelli di cui alla voce 08 03 12", p: false },
  { c: "08 03 17", d: "Toner per stampa esauriti contenenti sostanze pericolose", p: true },
  { c: "08 03 18", d: "Toner per stampa esauriti diversi da quelli di cui alla voce 08 03 17", p: false },
  { c: "08 04 09", d: "Adesivi e sigillanti di scarto contenenti solventi organici o altre sostanze pericolose", p: true },
  { c: "08 04 10", d: "Adesivi e sigillanti di scarto diversi da quelli di cui alla voce 08 04 09", p: false },
  { c: "08 05 01", d: "Isocianati di scarto", p: true },

  /* ---------- 09 ---------- */
  { c: "09", d: "Rifiuti dell'industria fotografica", ch: true },
  { c: "09 01 01", d: "Soluzioni di sviluppo e attivanti a base acquosa", p: true },
  { c: "09 01 04", d: "Soluzioni di fissaggio", p: true },
  { c: "09 01 07", d: "Carta e pellicole per fotografia, contenenti argento o composti dell'argento", p: false },
  { c: "09 01 08", d: "Carta e pellicole per fotografia, non contenenti argento o composti dell'argento", p: false },

  /* ---------- 10 ---------- */
  { c: "10", d: "Rifiuti provenienti da processi termici", ch: true },
  { c: "10 01 01", d: "Ceneri pesanti, scorie e polveri di caldaia (tranne 10 01 04)", p: false },
  { c: "10 01 02", d: "Ceneri leggere di carbone", p: false },
  { c: "10 01 15", d: "Ceneri pesanti, scorie e polveri di caldaia da co-incenerimento, diverse da quelle di cui alla voce 10 01 14", p: false },
  { c: "10 02 01", d: "Rifiuti del trattamento delle scorie", p: false },
  { c: "10 02 10", d: "Scaglie di laminazione", p: false },
  { c: "10 09 06", d: "Forme e anime da fonderia non utilizzate, diverse da quelle di cui alla voce 10 09 05", p: false },
  { c: "10 09 08", d: "Forme e anime da fonderia utilizzate, diverse da quelle di cui alla voce 10 09 07", p: false },
  { c: "10 11 12", d: "Rifiuti di vetro diversi da quelli di cui alla voce 10 11 11", p: false },
  { c: "10 12 08", d: "Scarti di ceramica, mattoni, mattonelle e materiali da costruzione (sottoposti a trattamento termico)", p: false },
  { c: "10 13 14", d: "Rifiuti e fanghi di cemento", p: false },

  /* ---------- 11 ---------- */
  { c: "11", d: "Rifiuti prodotti dal trattamento chimico superficiale e dal rivestimento di metalli e altri materiali; idrometallurgia non ferrosa", ch: true },
  { c: "11 01 05", d: "Acidi di decappaggio", p: true },
  { c: "11 01 06", d: "Acidi non specificati altrimenti", p: true },
  { c: "11 01 08", d: "Fanghi di fosfatazione", p: true },
  { c: "11 01 09", d: "Fanghi e residui di filtrazione contenenti sostanze pericolose", p: true },
  { c: "11 01 10", d: "Fanghi e residui di filtrazione diversi da quelli di cui alla voce 11 01 09", p: false },
  { c: "11 01 11", d: "Soluzioni acquose di lavaggio contenenti sostanze pericolose", p: true },
  { c: "11 01 12", d: "Soluzioni acquose di lavaggio diverse da quelle di cui alla voce 11 01 11", p: false },
  { c: "11 01 13", d: "Rifiuti di sgrassaggio contenenti sostanze pericolose", p: true },
  { c: "11 05 01", d: "Zinco solido", p: false },

  /* ---------- 12 ---------- */
  { c: "12", d: "Rifiuti prodotti dalla lavorazione e dal trattamento fisico e meccanico superficiale di metalli e plastica", ch: true },
  { c: "12 01 01", d: "Limatura e trucioli di materiali ferrosi", p: false },
  { c: "12 01 02", d: "Polveri e particolato di materiali ferrosi", p: false },
  { c: "12 01 03", d: "Limatura e trucioli di materiali non ferrosi", p: false },
  { c: "12 01 04", d: "Polveri e particolato di materiali non ferrosi", p: false },
  { c: "12 01 05", d: "Limatura e trucioli di materiali plastici", p: false },
  { c: "12 01 06", d: "Oli minerali per macchinari, contenenti alogeni (eccetto emulsioni e soluzioni)", p: true },
  { c: "12 01 07", d: "Oli minerali per macchinari, non contenenti alogeni (eccetto emulsioni e soluzioni)", p: true },
  { c: "12 01 08", d: "Emulsioni e soluzioni per macchinari, contenenti alogeni", p: true },
  { c: "12 01 09", d: "Emulsioni e soluzioni per macchinari, non contenenti alogeni", p: true },
  { c: "12 01 10", d: "Oli sintetici per macchinari", p: true },
  { c: "12 01 12", d: "Cere e grassi esauriti", p: true },
  { c: "12 01 13", d: "Rifiuti di saldatura", p: false },
  { c: "12 01 14", d: "Fanghi di lavorazione contenenti sostanze pericolose", p: true },
  { c: "12 01 15", d: "Fanghi di lavorazione diversi da quelli di cui alla voce 12 01 14", p: false },
  { c: "12 01 17", d: "Materiale abrasivo di scarto, diverso da quello di cui alla voce 12 01 16", p: false },
  { c: "12 01 18", d: "Fanghi metallici (fanghi di rettifica, affilatura e lappatura) contenenti olio", p: true },
  { c: "12 01 20", d: "Corpi d'utensile e materiali di rettifica esauriti, contenenti sostanze pericolose", p: true },
  { c: "12 01 21", d: "Corpi d'utensile e materiali di rettifica esauriti, diversi da quelli di cui alla voce 12 01 20", p: false },
  { c: "12 03 01", d: "Soluzioni acquose di lavaggio", p: true },

  /* ---------- 13 ---------- */
  { c: "13", d: "Oli esauriti e residui di combustibili liquidi (tranne oli commestibili e capitoli 05, 12 e 19)", ch: true },
  { c: "13 01 10", d: "Oli minerali per circuiti idraulici, non clorurati", p: true },
  { c: "13 01 11", d: "Oli sintetici per circuiti idraulici", p: true },
  { c: "13 01 13", d: "Altri oli per circuiti idraulici", p: true },
  { c: "13 02 05", d: "Scarti di olio minerale per motori, ingranaggi e lubrificazione, non clorurati", p: true },
  { c: "13 02 06", d: "Scarti di olio sintetico per motori, ingranaggi e lubrificazione", p: true },
  { c: "13 02 08", d: "Altri oli per motori, ingranaggi e lubrificazione", p: true },
  { c: "13 03 07", d: "Oli minerali non clorurati isolanti e termoconduttori", p: true },
  { c: "13 03 10", d: "Altri oli isolanti e termoconduttori", p: true },
  { c: "13 05 01", d: "Rifiuti solidi delle camere a sabbia e di prodotti di separazione olio/acqua", p: true },
  { c: "13 05 02", d: "Fanghi di prodotti di separazione olio/acqua", p: true },
  { c: "13 05 03", d: "Fanghi da collettori", p: true },
  { c: "13 05 06", d: "Oli prodotti dalla separazione olio/acqua", p: true },
  { c: "13 05 07", d: "Acque oleose prodotte dalla separazione olio/acqua", p: true },
  { c: "13 05 08", d: "Miscugli di rifiuti delle camere a sabbia e dei prodotti di separazione olio/acqua", p: true },
  { c: "13 07 01", d: "Olio combustibile e carburante diesel", p: true },
  { c: "13 07 03", d: "Altri carburanti (comprese le miscele)", p: true },
  { c: "13 08 02", d: "Altre emulsioni", p: true },
  { c: "13 08 99", d: "Rifiuti non specificati altrimenti (oli esauriti)", p: true },

  /* ---------- 14 ---------- */
  { c: "14", d: "Solventi organici, refrigeranti e propellenti di scarto (tranne capitoli 07 e 08)", ch: true },
  { c: "14 06 01", d: "Clorofluorocarburi, HCFC, HFC", p: true },
  { c: "14 06 02", d: "Altri solventi e miscele di solventi, alogenati", p: true },
  { c: "14 06 03", d: "Altri solventi e miscele di solventi", p: true },
  { c: "14 06 04", d: "Fanghi o rifiuti solidi contenenti solventi alogenati", p: true },
  { c: "14 06 05", d: "Fanghi o rifiuti solidi contenenti altri solventi", p: true },

  /* ---------- 15 ---------- */
  { c: "15", d: "Rifiuti di imballaggio; assorbenti, stracci, materiali filtranti e indumenti protettivi (non specificati altrimenti)", ch: true },
  { c: "15 01 01", d: "Imballaggi in carta e cartone", p: false },
  { c: "15 01 02", d: "Imballaggi in plastica", p: false },
  { c: "15 01 03", d: "Imballaggi in legno", p: false },
  { c: "15 01 04", d: "Imballaggi metallici", p: false },
  { c: "15 01 05", d: "Imballaggi in materiali compositi", p: false },
  { c: "15 01 06", d: "Imballaggi in materiali misti", p: false },
  { c: "15 01 07", d: "Imballaggi in vetro", p: false },
  { c: "15 01 09", d: "Imballaggi in materia tessile", p: false },
  { c: "15 01 10", d: "Imballaggi contenenti residui di sostanze pericolose o contaminati da tali sostanze", p: true },
  { c: "15 01 11", d: "Imballaggi metallici contenenti matrici solide porose pericolose (es. amianto), compresi contenitori a pressione vuoti", p: true },
  { c: "15 02 02", d: "Assorbenti, materiali filtranti (inclusi filtri dell'olio), stracci e indumenti protettivi contaminati da sostanze pericolose", p: true },
  { c: "15 02 03", d: "Assorbenti, materiali filtranti, stracci e indumenti protettivi diversi da quelli di cui alla voce 15 02 02", p: false },

  /* ---------- 16 ---------- */
  { c: "16", d: "Rifiuti non specificati altrimenti nell'elenco", ch: true },
  { c: "16 01 03", d: "Pneumatici fuori uso", p: false },
  { c: "16 01 07", d: "Filtri dell'olio", p: true },
  { c: "16 01 11", d: "Pastiglie per freni contenenti amianto", p: true },
  { c: "16 01 12", d: "Pastiglie per freni diverse da quelle di cui alla voce 16 01 11", p: false },
  { c: "16 01 13", d: "Liquidi per freni", p: true },
  { c: "16 01 14", d: "Liquidi antigelo contenenti sostanze pericolose", p: true },
  { c: "16 01 15", d: "Liquidi antigelo diversi da quelli di cui alla voce 16 01 14", p: false },
  { c: "16 01 17", d: "Metalli ferrosi", p: false },
  { c: "16 01 18", d: "Metalli non ferrosi", p: false },
  { c: "16 01 19", d: "Plastica", p: false },
  { c: "16 01 20", d: "Vetro", p: false },
  { c: "16 02 13", d: "Apparecchiature fuori uso contenenti componenti pericolosi, diverse da quelle di cui alle voci da 16 02 09 a 16 02 12", p: true },
  { c: "16 02 14", d: "Apparecchiature fuori uso, diverse da quelle di cui alle voci da 16 02 09 a 16 02 13", p: false },
  { c: "16 02 15", d: "Componenti pericolosi rimossi da apparecchiature fuori uso", p: true },
  { c: "16 02 16", d: "Componenti rimossi da apparecchiature fuori uso, diversi da quelli di cui alla voce 16 02 15", p: false },
  { c: "16 03 05", d: "Rifiuti organici contenenti sostanze pericolose", p: true },
  { c: "16 03 06", d: "Rifiuti organici, diversi da quelli di cui alla voce 16 03 05", p: false },
  { c: "16 05 04", d: "Gas in contenitori a pressione (compresi gli halon) contenenti sostanze pericolose", p: true },
  { c: "16 05 05", d: "Gas in contenitori a pressione, diversi da quelli di cui alla voce 16 05 04", p: false },
  { c: "16 05 06", d: "Sostanze chimiche di laboratorio contenenti o costituite da sostanze pericolose", p: true },
  { c: "16 05 07", d: "Sostanze chimiche inorganiche di scarto contenenti o costituite da sostanze pericolose", p: true },
  { c: "16 05 08", d: "Sostanze chimiche organiche di scarto contenenti o costituite da sostanze pericolose", p: true },
  { c: "16 06 01", d: "Batterie al piombo", p: true },
  { c: "16 06 02", d: "Batterie al nichel-cadmio", p: true },
  { c: "16 06 03", d: "Batterie contenenti mercurio", p: true },
  { c: "16 06 04", d: "Batterie alcaline (tranne 16 06 03)", p: false },
  { c: "16 06 05", d: "Altre batterie e accumulatori", p: false },
  { c: "16 07 08", d: "Rifiuti contenenti olio", p: true },
  { c: "16 07 09", d: "Rifiuti contenenti altre sostanze pericolose", p: true },
  { c: "16 10 01", d: "Soluzioni acquose di scarto contenenti sostanze pericolose", p: true },
  { c: "16 10 02", d: "Soluzioni acquose di scarto, diverse da quelle di cui alla voce 16 10 01", p: false },
  { c: "16 11 06", d: "Rivestimenti e materiali refrattari da lavorazioni non metallurgiche, diversi da quelli di cui alla voce 16 11 05", p: false },

  /* ---------- 17 ---------- */
  { c: "17", d: "Rifiuti delle operazioni di costruzione e demolizione (compreso il terreno proveniente da siti contaminati)", ch: true },
  { c: "17 01 01", d: "Cemento", p: false },
  { c: "17 01 02", d: "Mattoni", p: false },
  { c: "17 01 03", d: "Mattonelle e ceramiche", p: false },
  { c: "17 01 06", d: "Miscugli o scorie di cemento, mattoni, mattonelle e ceramiche contenenti sostanze pericolose", p: true },
  { c: "17 01 07", d: "Miscugli di cemento, mattoni, mattonelle e ceramiche, diversi da quelli di cui alla voce 17 01 06", p: false },
  { c: "17 02 01", d: "Legno", p: false },
  { c: "17 02 02", d: "Vetro", p: false },
  { c: "17 02 03", d: "Plastica", p: false },
  { c: "17 02 04", d: "Vetro, plastica e legno contenenti sostanze pericolose o da esse contaminati", p: true },
  { c: "17 03 01", d: "Miscele bituminose contenenti catrame di carbone", p: true },
  { c: "17 03 02", d: "Miscele bituminose diverse da quelle di cui alla voce 17 03 01", p: false },
  { c: "17 04 01", d: "Rame, bronzo, ottone", p: false },
  { c: "17 04 02", d: "Alluminio", p: false },
  { c: "17 04 03", d: "Piombo", p: false },
  { c: "17 04 05", d: "Ferro e acciaio", p: false },
  { c: "17 04 07", d: "Metalli misti", p: false },
  { c: "17 04 09", d: "Rifiuti metallici contaminati da sostanze pericolose", p: true },
  { c: "17 04 10", d: "Cavi, impregnati di olio, di catrame di carbone o di altre sostanze pericolose", p: true },
  { c: "17 04 11", d: "Cavi, diversi da quelli di cui alla voce 17 04 10", p: false },
  { c: "17 05 03", d: "Terra e rocce contenenti sostanze pericolose", p: true },
  { c: "17 05 04", d: "Terra e rocce, diverse da quelle di cui alla voce 17 05 03", p: false },
  { c: "17 05 06", d: "Fanghi di dragaggio, diversi da quelli di cui alla voce 17 05 05", p: false },
  { c: "17 06 01", d: "Materiali isolanti contenenti amianto", p: true },
  { c: "17 06 03", d: "Altri materiali isolanti contenenti o costituiti da sostanze pericolose", p: true },
  { c: "17 06 04", d: "Materiali isolanti diversi da quelli di cui alle voci 17 06 01 e 17 06 03", p: false },
  { c: "17 06 05", d: "Materiali da costruzione contenenti amianto", p: true },
  { c: "17 08 02", d: "Materiali da costruzione a base di gesso diversi da quelli di cui alla voce 17 08 01", p: false },
  { c: "17 09 03", d: "Altri rifiuti dell'attività di costruzione e demolizione contenenti sostanze pericolose", p: true },
  { c: "17 09 04", d: "Rifiuti misti dell'attività di costruzione e demolizione, diversi da quelli di cui alle voci 17 09 01, 17 09 02 e 17 09 03", p: false },

  /* ---------- 18 ---------- */
  { c: "18", d: "Rifiuti prodotti dal settore sanitario e veterinario o da attività di ricerca collegate", ch: true },
  { c: "18 01 01", d: "Oggetti da taglio (eccetto 18 01 03)", p: false },
  { c: "18 01 03", d: "Rifiuti che devono essere raccolti e smaltiti applicando precauzioni particolari per evitare infezioni", p: true },
  { c: "18 01 04", d: "Rifiuti che non devono essere raccolti e smaltiti applicando precauzioni particolari per evitare infezioni", p: false },
  { c: "18 01 06", d: "Sostanze chimiche pericolose o contenenti sostanze pericolose", p: true },
  { c: "18 01 08", d: "Medicinali citotossici e citostatici", p: true },
  { c: "18 01 09", d: "Medicinali diversi da quelli di cui alla voce 18 01 08", p: false },
  { c: "18 02 02", d: "Rifiuti che devono essere raccolti e smaltiti applicando precauzioni particolari per evitare infezioni (veterinari)", p: true },

  /* ---------- 19 ---------- */
  { c: "19", d: "Rifiuti prodotti da impianti di trattamento rifiuti, impianti di trattamento acque reflue fuori sito e potabilizzazione", ch: true },
  { c: "19 02 05", d: "Fanghi prodotti da trattamenti chimico-fisici, contenenti sostanze pericolose", p: true },
  { c: "19 02 06", d: "Fanghi prodotti da trattamenti chimico-fisici, diversi da quelli di cui alla voce 19 02 05", p: false },
  { c: "19 08 01", d: "Vaglio", p: false },
  { c: "19 08 02", d: "Rifiuti dell'eliminazione della sabbia", p: false },
  { c: "19 08 05", d: "Fanghi prodotti dal trattamento delle acque reflue urbane", p: false },
  { c: "19 08 09", d: "Miscele di oli e grassi prodotte dalla separazione olio/acqua, contenenti oli e grassi commestibili", p: false },
  { c: "19 08 10", d: "Miscele di oli e grassi prodotte dalla separazione olio/acqua, diverse da quelle di cui alla voce 19 08 09", p: true },
  { c: "19 08 14", d: "Fanghi prodotti da altri trattamenti delle acque reflue industriali, diversi da quelli di cui alla voce 19 08 13", p: false },
  { c: "19 09 02", d: "Fanghi prodotti dai processi di chiarificazione dell'acqua", p: false },
  { c: "19 12 01", d: "Carta e cartone", p: false },
  { c: "19 12 02", d: "Metalli ferrosi", p: false },
  { c: "19 12 03", d: "Metalli non ferrosi", p: false },
  { c: "19 12 04", d: "Plastica e gomma", p: false },
  { c: "19 12 05", d: "Vetro", p: false },
  { c: "19 12 07", d: "Legno diverso da quello di cui alla voce 19 12 06", p: false },
  { c: "19 12 10", d: "Rifiuti combustibili (CDR: combustibile derivato da rifiuti)", p: false },
  { c: "19 12 12", d: "Altri rifiuti (compresi materiali misti) prodotti dal trattamento meccanico dei rifiuti, diversi da quelli di cui alla voce 19 12 11", p: false },
  { c: "19 13 02", d: "Rifiuti solidi prodotti dalle operazioni di bonifica dei terreni, diversi da quelli di cui alla voce 19 13 01", p: false },

  /* ---------- 20 ---------- */
  { c: "20", d: "Rifiuti urbani (rifiuti domestici e assimilabili prodotti da attività commerciali e industriali nonché dalle istituzioni), inclusa la raccolta differenziata", ch: true },
  { c: "20 01 01", d: "Carta e cartone", p: false },
  { c: "20 01 02", d: "Vetro", p: false },
  { c: "20 01 08", d: "Rifiuti biodegradabili di cucine e mense", p: false },
  { c: "20 01 10", d: "Abbigliamento", p: false },
  { c: "20 01 11", d: "Prodotti tessili", p: false },
  { c: "20 01 13", d: "Solventi", p: true },
  { c: "20 01 14", d: "Acidi", p: true },
  { c: "20 01 15", d: "Sostanze alcaline", p: true },
  { c: "20 01 17", d: "Prodotti fotochimici", p: true },
  { c: "20 01 19", d: "Pesticidi", p: true },
  { c: "20 01 21", d: "Tubi fluorescenti e altri rifiuti contenenti mercurio", p: true },
  { c: "20 01 23", d: "Apparecchiature fuori uso contenenti clorofluorocarburi", p: true },
  { c: "20 01 25", d: "Oli e grassi commestibili", p: false },
  { c: "20 01 26", d: "Oli e grassi diversi da quelli di cui alla voce 20 01 25", p: true },
  { c: "20 01 27", d: "Vernici, inchiostri, adesivi e resine contenenti sostanze pericolose", p: true },
  { c: "20 01 28", d: "Vernici, inchiostri, adesivi e resine diversi da quelli di cui alla voce 20 01 27", p: false },
  { c: "20 01 32", d: "Medicinali diversi da quelli di cui alla voce 20 01 31", p: false },
  { c: "20 01 33", d: "Batterie e accumulatori di cui alle voci 16 06 01, 16 06 02 e 16 06 03, nonché batterie e accumulatori non suddivisi contenenti tali batterie", p: true },
  { c: "20 01 34", d: "Batterie e accumulatori diversi da quelli di cui alla voce 20 01 33", p: false },
  { c: "20 01 35", d: "Apparecchiature elettriche ed elettroniche fuori uso contenenti componenti pericolosi, diverse da quelle di cui alle voci 20 01 21 e 20 01 23", p: true },
  { c: "20 01 36", d: "Apparecchiature elettriche ed elettroniche fuori uso, diverse da quelle di cui alle voci 20 01 21, 20 01 23 e 20 01 35", p: false },
  { c: "20 01 38", d: "Legno diverso da quello di cui alla voce 20 01 37", p: false },
  { c: "20 01 39", d: "Plastica", p: false },
  { c: "20 01 40", d: "Metallo", p: false },
  { c: "20 02 01", d: "Rifiuti biodegradabili (giardini e parchi)", p: false },
  { c: "20 03 01", d: "Rifiuti urbani non differenziati", p: false },
  { c: "20 03 03", d: "Residui della pulizia stradale", p: false },
  { c: "20 03 04", d: "Fanghi delle fosse settiche", p: false },
  { c: "20 03 06", d: "Rifiuti della pulizia delle fognature", p: false },
  { c: "20 03 07", d: "Rifiuti ingombranti", p: false },
];
